services:
  db:
    image: mongo
    container_name: controle-de-corrida-db
    networks:
      - appnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017

  api:
    build: .
    container_name: controle-de-corrida-api
    entrypoint: >
      /bin/bash -c '
      openssl rand -base64 756 > /data/keyfile.key &&
      chmod 400 /data/keyfile.key &&
      chown mongodb:mongodb /data/keyfile.key &&
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keyfile.key --bind_ip_all'
    networks:
      - appnet
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000 
    environment:
      - DATABASE_URL=mongodb://root:root@mongo:27017/controle_de_corrida?authSource=admin  

networks:
  appnet:
    driver: bridge